import { hasSupabaseConfig, supabase } from './lib/supabase.js';

'use strict';
const CATEGORIES = [
{id:'jazz',name:'Jazz',color:'#b0813d'},{id:'electronic',name:'Elektronisk/rave',color:'#8e70b1'},
{id:'rock',name:'Rock og pop',color:'#be705c'},{id:'classical',name:'Klassisk',color:'#7784a6'},
{id:'art',name:'Utstillinger',color:'#bf888e'},{id:'theatre',name:'Teater og scene',color:'#997488'},
{id:'film',name:'Film',color:'#6d8598'},{id:'comedy',name:'Stand-up',color:'#b59a42'},
{id:'food',name:'Mat og drikke',color:'#ba805a'},{id:'market',name:'Marked og loppis',color:'#9d9265'},
{id:'talk',name:'Foredrag og debatt',color:'#748c91'},{id:'sport',name:'Sport',color:'#608c88'},
{id:'outdoor',name:'Friluft',color:'#769061'},{id:'family',name:'Barn og familie',color:'#ad9274'},
{id:'books',name:'Litteratur',color:'#897562'},{id:'nightlife',name:'Klubb og uteliv',color:'#7a79a5'},
{id:'other',name:'Annet',color:'#8a8d86'}
];
const AVATAR_COLORS='76a7ff,75c675,ffaa64,ff4d6f,af61f2';
const ALLOWED_IMAGE_TYPES=new Set(['image/png','image/jpeg','image/webp','image/gif']);
const EVENT_IMAGES=[
 {id:'green',label:'Grønt og turkis',src:'bilder/bakgrunn-1.png'},
 {id:'yellow',label:'Gult og lilla',src:'bilder/bakgrunn-2.png'},
 {id:'blue',label:'Blått og lilla',src:'bilder/bakgrunn-3.png'},
 {id:'red',label:'Rødt og oransje',src:'bilder/bakgrunn-4.png'}
];
const USER={id:null,email:'',firstName:'',lastName:'',district:'',avatarPath:null,customAvatar:'',get name(){return `${this.firstName} ${this.lastName}`.trim()||'Din profil'}};
const FRIENDS=[{id:'miriam',name:'Miriam Lund',initials:'ML',avatarSeed:'Miriam'},{id:'jonas',name:'Jonas Berg',initials:'JB',avatarSeed:'Jonas'},{id:'sara',name:'Sara Holm',initials:'SH',avatarSeed:'Sara'},{id:'emil',name:'Emil Solstad',initials:'ES',avatarSeed:'Emil'}];
const PARTICIPANTS=[...FRIENDS,{id:'ida',name:'Ida Nilsen',avatarSeed:'Ida'},{id:'ahmed',name:'Ahmed Noor',avatarSeed:'Ahmed'},{id:'eline',name:'Eline Vik',avatarSeed:'Eline'},{id:'mathias',name:'Mathias Lie',avatarSeed:'Mathias'},{id:'nora',name:'Nora Berg',avatarSeed:'Nora'},{id:'thea',name:'Thea Solheim',avatarSeed:'Thea'}];
const CENTER=[59.913,10.752];
const osloParts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Oslo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
const part=t=>osloParts.find(p=>p.type===t).value;
const TODAY=`${part('year')}-${part('month')}-${part('day')}`;
const plusDays=(date,n)=>new Date(Date.parse(date+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
const weekday=new Date(TODAY+'T12:00:00Z').getUTCDay();
const saturdayOffset=weekday===0?0:6-weekday;
const weekendStart=plusDays(TODAY,saturdayOffset);
const weekendEnd=plusDays(weekendStart,weekday===0?1:2);
const stamp=(offset,time)=>`${plusDays(TODAY,offset)}T${time}:00`;
// ── MOCK-DATA: Én tydelig event-array. Kortformat ekspanderes til event-objekter. ──
// [tittel, kategori-id, sted, lat, lng, dag-offset, start, slutt, pris, beskrivelse]
const MOCK_EVENTS = [
['Bakgårdstoner','jazz','Bakgård 17 · Grünerløkka',59.9218,10.7590,0,'14:00','16:00','Gratis','En varm trio, nytraktet kaffe og god plass mellom bordene. Kom innom for en rolig stund i bakgården.'],
['Analog ettermiddag','electronic','Frekvensrommet · Tøyen',59.9166,10.7758,0,'16:00','19:00','120 kr','Lokale selektører spiller myke rytmer og rare favoritter. En lyttesesjon før kvelden begynner.'],
['Små band, stor lyd','rock','Forsterkeren · Vulkan',59.9228,10.7514,0,'18:00','21:00','180 kr','Tre fiktive Oslo-band deler scene og forsterkere. Gitarpop, nye låter og en liten dose støy.'],
['Stryk i salongen','classical','Salong Vest · Frogner',59.9186,10.7056,0,'15:00','16:30','150 kr','En strykekvartett inviterer til en uformell kammerkonsert. Musikken introduseres fra scenen.'],
['Mellom husene','art','Galleri Mellomrom · Bjørvika',59.9067,10.7598,0,'11:00','17:00','Gratis','Fotografier av oversette steder i en by som forandrer seg. Kunstnerprat hver hele time.'],
['En plass ved vinduet','theatre','Sidescenen · Sagene',59.9392,10.7542,0,'18:30','20:00','220 kr','En liten forestilling om naboer som aldri har hilst. Nært teater med plass til førti gjester.'],
['Ettermiddag i mørket','film','Lille Lerret · Majorstuen',59.9292,10.7145,0,'17:00','19:00','110 kr','En oppdiktet kortfilmserie om tilfeldige møter. Kort samtale med filmskaperne etter visningen.'],
['Fem minutter til','comedy','Kjellerlatter · Sentrum',59.9162,10.7446,0,'19:00','21:00','100 kr','Nye komikere tester ferske historier i en liten kjeller. Kveldens vert binder det hele sammen.'],
['Langbord ved elva','food','Elvebordet · Vulkan',59.9237,10.7529,0,'13:00','16:00','250 kr','Del småretter laget av sesongens grønnsaker. Det er lov å komme alene til langbordet.'],
['Skatter fra loftet','market','Gårdsplassen · Bislett',59.9278,10.7337,0,'10:00','15:00','Gratis','Bruktfunn, gamle plater og småting med en historie. Nabolaget rydder på loftet.'],
['Hvem eier byrommet?','talk','Samtalerommet · Tøyen',59.9192,10.7721,0,'17:30','19:00','Gratis','En åpen samtale om benker, møteplasser og plass til alle. Publikum inviteres til å stille spørsmål.'],
['Ball i parken','sport','Løkka aktivitetsplass · Grünerløkka',59.9260,10.7644,0,'16:30','18:00','Gratis','Uformelle småkamper for voksne på alle nivåer. Vi deler inn lag når alle har kommet.'],
['En rolig runde ved fjorden','outdoor','Bryggekroken · Tjuvholmen',59.9068,10.7219,0,'12:00','13:30','Gratis','En sosial rusletur langs vannet med en pause underveis. Ta med gode sko og noe varmt på termos.'],
['Små arkitekter','family','Verksted Frø · Sagene',59.9373,10.7601,0,'11:00','14:00','60 kr','Bygg en liten fantasiby av papp og gjenbruksmaterialer. Passer for barn fra fire år sammen med en voksen.'],
['En bok, en kopp','books','Bokstua Nord · St. Hanshaugen',59.9261,10.7431,0,'14:30','16:00','Gratis','Ta med en bok du vil anbefale og møt andre lesere. Det kreves ingen forberedelser.'],
['En siste dans','nightlife','Rom 23 · Sentrum',59.9141,10.7475,0,'20:00','23:30','150 kr','En tidlig klubbkveld med disco og myk house. Dansegulvet åpner mens byen fortsatt er våken.'],
['Blåtime på hjørnet','jazz','Hjørnesalongen · Bislett',59.9239,10.7365,1,'19:00','21:00','140 kr','Piano og kontrabass i en intim hjørnesalong. En kveld med improvisasjon og melodier du nesten kjenner.'],
['Papir, lys og skygge','art','Atelier Linje · Frogner',59.9222,10.7117,1,'12:00','18:00','Gratis','Små papirarbeider blir til store skygger. En sanselig utstilling med lokale, fiktive kunstnere.'],
['Et bord for seks','food','Kjøkken Nabo · Sagene',59.9420,10.7504,1,'18:00','20:00','295 kr','En uformell suppemiddag rundt små fellesbord. Menyen tar utgangspunkt i høstens råvarer.'],
['Film fra en annen gate','film','Projektorloftet · Grünerløkka',59.9245,10.7624,1,'18:30','20:30','90 kr','Et oppdiktet dokumentarprogram om hverdag og byliv. Vi avslutter med en samtale over en kopp te.'],
['Løp og prat','sport','Startstreken · Majorstuen',59.9291,10.7068,1,'17:00','18:00','Gratis','Fem rolige kilometer med pratetempo og felles start. Ingen blir stående igjen.'],
['Ord ved elva','books','Leserom Elv · Vulkan',59.9253,10.7527,1,'19:00','20:30','80 kr','Tre nye stemmer leser dikt og korte tekster. Kvelden avsluttes med åpen mikrofon.'],
['Byen etter 2030','talk','Forum Sør · Bjørvika',59.9053,10.7661,1,'17:00','18:30','Gratis','En fiktiv panelsamtale om hvordan vi vil bo og møtes. Kom med spørsmål og egne ideer.'],
['Fortellinger på gulvet','family','Lille Loft · Tøyen',59.9212,10.7793,1,'16:00','17:00','Gratis','Høytlesning, rare figurer og puter på gulvet. For barn fra tre til sju år med følge.'],
['Et lite synthesizerorkester','electronic','Kretsen · Grünerløkka',59.9290,10.7602,2,'19:00','22:00','160 kr','Fire musikere kobler seg sammen til et midlertidig orkester. Lydene bygges opp fra bunnen av.'],
['Scener fra et borettslag','theatre','Prøverommet · Bislett',59.9287,10.7374,2,'19:00','20:30','190 kr','En ny tekst prøves foran publikum for første gang. Etterpå er det rom for spørsmål.'],
['Plater og papir','market','Passasjen · Sentrum',59.9155,10.7558,3,'15:00','19:00','Gratis','En liten messe for vinyl, bøker og trykksaker. Her finnes både rimelige funn og samlerobjekter.'],
['Latter langs linja','comedy','Spor 4 · Majorstuen',59.9308,10.7187,3,'20:00','22:00','130 kr','Fire komikere og en gjest tar over det lille scenerommet. En uformell kveld med nye sett.'],
['Piano i skumringen','classical','Lille Aula · Frogner',59.9149,10.7091,4,'18:00','19:30','175 kr','En solopianist spiller korte stykker fra flere epoker. Programmet presenteres underveis.'],
['Gitarer under taket','rock','Loftscene 8 · Tøyen',59.9158,10.7804,4,'19:30','22:00','200 kr','To fiktive band deler en liten loftscene. For deg som liker melodier med litt kant.'],
['Grønn omvei','outdoor','Turpunkt Elv · Sagene',59.9451,10.7622,5,'17:00','19:00','Gratis','Vi følger små stier og grønne lommer gjennom byen. Rolig tempo og stopp for å se oss rundt.'],
['Nattens sidespor','nightlife','Sidespor · Grønland',59.9143,10.7671,5,'21:00','23:55','180 kr','Lokale DJ-er deler plater de sjelden får spilt. Et lite dansegulv med god lyd.'],
['Helgefunn på hjørnet','market','Nabotorget · Sagene',59.9385,10.7478,saturdayOffset,'11:00','16:00','Gratis','Klær, kopper og små møbler bytter hender. Kaffe og vafler i den gamle porten.'],
['Smaker fra bakgården','food','Gryteriet · Grønland',59.9128,10.7692,saturdayOffset,'14:00','18:00','175 kr','En liten matvandring mellom fire boder i samme bakgård. Smaksbilletten gir en liten rett fra hver.'],
['Åpne atelierer øst','art','Atelier Rekke · Tøyen',59.9231,10.7754,saturdayOffset+(weekday===0?0:1),'12:00','17:00','Gratis','Besøk verkstedene bak de anonyme dørene. Se skisser, ferdige arbeider og prosjekter underveis.'],
['Byen i miniatyr','family','Byverkstedet · Bjørvika',59.9044,10.7619,saturdayOffset+(weekday===0?0:1),'12:00','15:00','75 kr','Vi bygger gater, broer og rare tårn i miniatyr. Et åpent verksted for hele familien.'],
['Kaffe og en runde i parken','outdoor','Parkhjørnet · St. Hanshaugen',59.9283,10.7459,0,'15:30','17:00','Gratis','En liten tur med venner før vi setter oss ned med kaffe. Ta med termos og godt humør.'],
['Middag hos Miriam','food','Miriams kjøkken · Grünerløkka',59.9231,10.7571,0,'18:00','21:00','Gratis','Vi lager middag sammen og deler det som står på bordet. Ta gjerne med noe godt å drikke.'],
['Lytteloft med Jonas','electronic','Jonas sitt loft · Sagene',59.9404,10.7560,1,'19:00','22:00','Gratis','Ta med tre spor du vil dele med resten av gjengen. Vi lytter fra start til slutt.'],
['Bokprat hos Sara','books','Saras stue · Frogner',59.9201,10.7164,saturdayOffset+(weekday===0?0:1),'16:00','18:00','Gratis','En uformell bokprat hjemme i stua. Ta med en bok du har likt i det siste.']
].map((row,index)=>{
 const [title,category,venue,lat,lng,day,start,end,price,description]=row;
 const privateEvent=index>=36;
 return {id:`e${index+1}`,title,category,description,venue,lat,lng,start:stamp(day,start),end:stamp(day,end),price,visibility:privateEvent?'private':'public',organizer:privateEvent?['Thorkild Stray','Miriam Lund','Jonas Berg','Sara Holm'][index-36]:venue.split(' · ')[0],creatorId:privateEvent?['me','miriam','jonas','sara'][index-36]:'community',attendees:privateEvent?4:8+(index*13)%84,source:privateEvent?'Bruker':['VisitOSLO','Oslo kommune','Bruker'][index%3],invitedIds:privateEvent?(index===36?['miriam','emil']:['me']):[],distance:((Math.abs(lat-CENTER[0])*75+Math.abs(lng-CENTER[1])*43)+.3).toFixed(1)};
});
// ── Tilstand og data er adskilt fra liste- og kartrendering. ──
const state={events:[...MOCK_EVENTS],interests:new Set(),period:'today',query:'',selected:null,going:new Set(),invitations:{e38:'pending',e39:'pending',e40:'pending'},friends:[],friendRequests:[],outgoing:{},draftLocation:null,draftImage:'',draftImagePreset:'green',draftExistingImagePath:null,draftRemoveImage:false,editingEventId:null,picking:false,inviteEvent:null};
let currentSession=null,authMode='login',interestSaveTimer=null,draftEventImageFile=null,sharedEventHandled=false,pendingInvitationToken=new URLSearchParams(location.search).get('invite');
const $=selector=>document.querySelector(selector);
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>`<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const avatarURL=seed=>`https://api.dicebear.com/10.x/glyphs/svg?glyphColor=${AVATAR_COLORS}&seed=${encodeURIComponent(seed)}`;
const userAvatarURL=()=>USER.customAvatar||avatarURL(USER.id||'guest');
const avatarImage=(seed,name,className='')=>`<img class="${className}" src="${avatarURL(seed)}" alt="Profilbilde for ${esc(name)}" width="48" height="48" loading="lazy">`;
const userAvatarImage=className=>`<img class="${className}" src="${userAvatarURL()}" alt="Profilbilde for ${esc(USER.name)}" width="48" height="48">`;
function updateAvatarUI(){const image=$('#header-avatar'),button=$('#profile-open');if(image)image.src=userAvatarURL();if(button)button.setAttribute('aria-label',currentSession?'Åpne profil':'Logg inn eller opprett profil');}
const publicAvatarURL=path=>path&&supabase?supabase.storage.from('avatars').getPublicUrl(path).data.publicUrl:'';
const osloLocalDateTime=iso=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Oslo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(iso));const value=type=>parts.find(part=>part.type===type).value;return `${value('year')}-${value('month')}-${value('day')}T${value('hour')}:${value('minute')}:${value('second')}`;};
const localDateTimeISO=(date,time)=>new Date(`${date}T${time}:00`).toISOString();
async function eventImageFromRow(row){if(!row.image_path)return EVENT_IMAGES.find(image=>image.id===row.image_preset)?.src||EVENT_IMAGES[0].src;const {data,error}=await supabase.storage.from('event-images').createSignedUrl(row.image_path,3600);return error?EVENT_IMAGES[0].src:data.signedUrl;}
async function loadEvents(){if(!supabase)return;if(currentSession){const invitations=await supabase.from('event_invitations').select('event_id, status').eq('invitee_id',USER.id);if(invitations.error){console.error(invitations.error);toast('Kunne ikke hente invitasjoner.');}else state.invitations=Object.fromEntries(invitations.data.map(invitation=>[invitation.event_id,invitation.status]));}else state.invitations={};const {data,error}=await supabase.from('events').select('id, creator_id, title, description, category, starts_at, ends_at, venue, latitude, longitude, price_text, image_path, image_preset, visibility, status, created_at, creator:profiles!events_creator_id_fkey(first_name, last_name)').eq('status','published').order('starts_at',{ascending:true});if(error){console.error(error);toast('Kunne ikke hente arrangementer.');return;}state.events=await Promise.all(data.map(async row=>{const organizer=[row.creator?.first_name,row.creator?.last_name].filter(Boolean).join(' ')||'Appventure-bruker';return {id:row.id,title:row.title,category:row.category,description:row.description,image:await eventImageFromRow(row),imagePath:row.image_path,imagePreset:row.image_preset,venue:row.venue,lat:row.latitude,lng:row.longitude,start:osloLocalDateTime(row.starts_at),end:osloLocalDateTime(row.ends_at),price:row.price_text,visibility:row.visibility,creatorId:row.creator_id,organizer,attendees:1,source:'Bruker',invitedIds:[],distance:(.3+Math.abs(row.latitude-CENTER[0])*75+Math.abs(row.longitude-CENTER[1])*43).toFixed(1)};}));render();const sharedEventId=new URLSearchParams(location.hash.slice(1)).get('event'),sharedEvent=state.events.find(event=>event.id===sharedEventId);if(sharedEvent&&!sharedEventHandled){sharedEventHandled=true;revealEvent(sharedEvent);}}
const eventImageURL=event=>{if(event.image)return event.image;const number=Number((event.id.match(/\d+/)||['1'])[0]);return EVENT_IMAGES[(Math.max(1,number)-1)%EVENT_IMAGES.length].src;};
function renderEventImagePresets(){const custom=!EVENT_IMAGES.some(option=>option.src===state.draftImage);$('#event-image-presets').innerHTML=EVENT_IMAGES.map(option=>`<button type="button" class="event-image-preset" data-event-image="${option.id}" role="radio" aria-checked="${!custom&&state.draftImage===option.src}" aria-label="${esc(option.label)}"><img src="${option.src}" alt="" width="160" height="100"></button>`).join('');}
const eventShareURL=event=>{const url=new URL(location.href);url.hash=`event=${encodeURIComponent(event.id)}`;return url.href;};
function openShareFallback(event){const url=eventShareURL(event),body=`${event.title}\n${dayLabel(event)} · ${timeText(event)}\n${event.venue}\n\n${url}`;$('#share-event-name').textContent=`Del «${event.title}»`;$('#share-link').value=url;$('#share-email').href=`mailto:?subject=${encodeURIComponent(`Appventure: ${event.title}`)}&body=${encodeURIComponent(body)}`;$('#share-dialog').showModal();}
async function shareEvent(event){const data={title:event.title,text:`${event.title} · ${dayLabel(event)} ${timeText(event)} · ${event.venue}`,url:eventShareURL(event)};if(navigator.share){try{await navigator.share(data);return}catch(error){if(error.name==='AbortError')return;}}openShareFallback(event);}
function participantRoster(event){const going=state.going.has(event.id),total=event.attendees+(going?1:0),number=Number((event.id.match(/\d+/)||['1'])[0]),ordered=PARTICIPANTS.map((_,index)=>PARTICIPANTS[(index+number)%PARTICIPANTS.length]),people=ordered.slice(0,Math.min(event.attendees,7));if(going)people.unshift({id:USER.id,name:USER.name,avatar:USER.customAvatar,avatarSeed:USER.id});return {total,people:people.slice(0,Math.min(total,8))};}
function openParticipants(event){const roster=participantRoster(event);$('#participants-event-name').textContent=`${roster.total} ${roster.total===1?'person skal':'personer skal'} på ${event.title}`;$('#participant-list').innerHTML=roster.people.map(person=>`<div class="participant">${person.id===USER.id?userAvatarImage('friend-avatar'):avatarImage(person.avatarSeed,person.name,'friend-avatar')}<div><strong>${esc(person.name)}</strong><small>${person.id===USER.id?'Deg':'Skal delta'}</small></div></div>`).join('')+(roster.total>roster.people.length?`<div class="participant-more">+ ${roster.total-roster.people.length} andre deltakere</div>`:'');$('#participants-dialog').showModal();}
const categoryOf=event=>CATEGORIES.find(c=>c.id===event.category);
const dateText=(date,options={day:'numeric',month:'short'})=>new Intl.DateTimeFormat('nb-NO',{timeZone:'UTC',...options}).format(new Date(date.slice(0,10)+'T12:00:00Z'));
const timeText=event=>`${event.start.slice(11,16)}–${event.end.slice(11,16)}${event.end.slice(0,10)!==event.start.slice(0,10)?' (+1 dag)':''}`;
const dayLabel=event=>event.start.startsWith(TODAY)?'I dag':event.start.startsWith(plusDays(TODAY,1))?'I morgen':dateText(event.start);
const dateRange=(period,customDate=TODAY)=>period==='custom'?[customDate,plusDays(customDate,1)]:period==='today'?[TODAY,plusDays(TODAY,1)]:period==='tomorrow'?[plusDays(TODAY,1),plusDays(TODAY,2)]:period==='week'?[TODAY,plusDays(TODAY,7)]:[weekendStart,weekendEnd];
function canSee(event,userId=USER.id,invitations=state.invitations){return event.visibility==='public'||event.creatorId===userId||invitations[event.id]==='accepted';}
function filterEvents(events,filters){
 const [from,to]=dateRange(filters.period,filters.customDate),query=filters.query.trim().toLocaleLowerCase('nb-NO');
 return events.filter(event=>canSee(event,USER.id,filters.invitations)&&filters.interests.has(event.category)&&event.start.slice(0,10)>=from&&event.start.slice(0,10)<to&&(!query||[event.title,event.venue,event.description,event.organizer,categoryOf(event).name].join(' ').toLocaleLowerCase('nb-NO').includes(query))).sort((a,b)=>a.start.localeCompare(b.start)||a.title.localeCompare(b.title,'nb'));
}
function chipHTML(category){return `<button class="chip" style="--category:${category.color}" data-category="${category.id}" aria-pressed="${state.interests.has(category.id)}"><span class="dot"></span>${esc(category.name)}</button>`;}
function renderInterests(){
 $('#interests').innerHTML=CATEGORIES.map(chipHTML).join('');
 const selected=CATEGORIES.filter(category=>state.interests.has(category.id)),names=selected.slice(0,2).map(category=>category.name);
 $('#interest-summary').textContent=!selected.length?'Ingen valgt ennå':selected.length<=2?names.join(' · '):`${names.join(' · ')} +${selected.length-2}`;
 $('#interest-toggle').textContent=selected.length?'Endre':'Velg';
 $('#select-all').textContent=state.interests.size===CATEGORIES.length?'Nullstill':'Velg alle';
 document.querySelectorAll('[data-time]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.time===state.period));
 if($('#profile-dialog').open)renderProfile();
}
function renderList(events,filters){
 const hasInterests=filters.interests.size>0;
 $('#result-count').textContent=hasInterests?`${events.length} ${events.length===1?'event':'events'} i nærheten`:'Ditt Oslo starter her';
 const [from,to]=dateRange(filters.period,filters.customDate);
 $('#date-label').textContent=filters.period==='week'?'Neste 7 dager':from===plusDays(to,-1)?dateText(from):`${dateText(from)} – ${dateText(plusDays(to,-1))}`;
 if(!hasInterests){$('#event-list').innerHTML=`<div class="empty"><div class="empty-icon">${icon('sliders')}</div><h2>Velg noen interesser for å se hva som skjer</h2><p>Jazz på et hjørne? Et nytt bruktfunn?<br>Du bestemmer hva som dukker opp.</p></div>`;return;}
 if(!events.length){$('#event-list').innerHTML=`<div class="empty"><div class="empty-icon">${icon('search')}</div><h2>Ingen treff akkurat her</h2><p>Prøv en annen dag, flere interesser eller et annet søkeord.</p>${filters.query?'<button class="secondary" id="clear-search" style="margin-top:15px">Tøm søket</button>':''}</div>`;return;}
 $('#event-list').innerHTML=events.map(event=>{const c=categoryOf(event);return `<button class="event-card${filters.selected===event.id?' active':''}" data-event="${event.id}" aria-label="Vis ${esc(event.title)} i kartet"><span class="event-card-layout"><img class="event-card-image" src="${eventImageURL(event)}" alt="" width="176" height="176" loading="lazy"><span class="event-card-content"><span class="eyebrow" style="--category:${c.color}"><span class="dot"></span>${esc(c.name)}</span><span class="event-card-title">${esc(event.title)}</span><span class="event-card-description">${esc(event.description)}</span><span class="event-meta">${dayLabel(event)} · ${timeText(event)}</span><span class="event-meta">${esc(event.venue)}</span><span class="event-foot"><span>${event.distance.replace('.',',')} km · <span class="privacy">${event.visibility==='private'?icon('lock')+'Privat':'Offentlig'}</span></span></span></span></span></button>`;}).join('');
}
let map=null,markerLayer=null,draftMarker=null,tileLayer=null;const markers=new Map();
function popupHTML(event){const c=categoryOf(event),owner=currentSession&&event.creatorId===USER.id;return `<article class="popup"><img class="popup-image" src="${eventImageURL(event)}" alt="Bilde for ${esc(event.title)}" width="800" height="450"><div class="eyebrow" style="--category:${c.color}"><span class="dot"></span>${esc(c.name)}${event.visibility==='private'?' · '+icon('lock')+' Privat':''}</div><h2>${esc(event.title)}</h2><div class="event-meta">${icon('clock')}${dayLabel(event)} · ${timeText(event)}</div><div class="event-meta">${icon('pin')}${esc(event.venue)}</div><p>${esc(event.description)}</p><div class="popup-stats"><strong>${esc(event.price)}</strong><span>${event.distance.replace('.',',')} km</span></div><div class="popup-actions"><button class="secondary" data-share="${event.id}">${icon('share')}Del</button>${owner&&event.visibility==='private'?`<button class="secondary" data-invite="${event.id}">${icon('people')}Inviter</button>`:''}${owner?`<button class="secondary" data-edit-event="${event.id}">${icon('edit')}Rediger</button><button class="secondary" data-delete-event="${event.id}">Slett</button>`:''}</div><div class="source-note">Arrangør: ${esc(event.organizer)}</div></article>`;}
function renderMap(events,filters){
 $('#map-help').hidden=filters.interests.size>0;
 $('#map-count').hidden=filters.interests.size===0;
 $('#map-count').innerHTML=icon('pin')+`${events.length} ${events.length===1?'event':'events'} på kartet`;
 if(!map)return;
 const openId=[...markers].find(([,m])=>m.isPopupOpen())?.[0];
 markerLayer.clearLayers();markers.clear();
 for(const event of events){const c=categoryOf(event);const marker=L.marker([event.lat,event.lng],{title:event.title,alt:event.title,icon:L.divIcon({className:'map-pin',html:`<div class="pin-core${filters.selected===event.id?' selected':''}" style="--category:${c.color}"><span>${event.visibility==='private'?icon('lock'):'·'}</span></div>`,iconSize:[30,36],iconAnchor:[15,33],popupAnchor:[0,-30]})}).bindPopup(popupHTML(event),{maxWidth:305,autoPanPaddingTopLeft:L.point(25,110),autoPanPaddingBottomRight:L.point(25,45)}).addTo(markerLayer);
 marker.on('click',()=>{state.selected=event.id;renderList(filterEvents(state.events,state),state);});markers.set(event.id,marker);
 }
 if(openId&&markers.has(openId))markers.get(openId).openPopup();
}
function render(){const events=filterEvents(state.events,state);renderInterests();renderList(events,state);renderMap(events,state);const pending=currentSession?Object.values(state.invitations).filter(v=>v==='pending').length:0;$('#invite-badge').textContent='!';$('#invite-badge').hidden=!pending;}
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3600);}
function authErrorMessage(error){if(!error)return 'Noe gikk galt. Prøv igjen.';if(error.message?.includes('Invalid login credentials'))return 'Feil e-post eller passord.';if(error.message?.includes('already registered'))return 'Denne e-postadressen er allerede registrert.';if(error.message?.includes('Email not confirmed'))return 'Bekreft e-postadressen før du logger inn.';return error.message||'Noe gikk galt. Prøv igjen.';}
function eventErrorMessage(error){if(error?.code==='42501')return 'Du har ikke tilgang til å lagre arrangementet (42501).';if(error?.code==='23503')return 'Arrangementet kunne ikke kobles til profilen din (23503).';if(error?.code==='23514')return 'Dato, klokkeslett eller et annet felt er ugyldig (23514).';if(error?.code==='PGRST204'||error?.code==='42703')return 'Databaseskjemaet mangler en nødvendig oppdatering.';return `${error?.message||'Ukjent feil'}${error?.code?` (${error.code})`:''}`;}
function showAuthMessage(message,isError=false){const element=$('#auth-message');element.textContent=message;element.hidden=!message;element.classList.toggle('error',isError);}
function setAuthMode(mode){authMode=mode;const signup=mode==='signup';$('#auth-title').textContent=signup?'Opprett profil':'Logg inn';$('#auth-signup-fields').hidden=!signup;$('#auth-form').elements.firstName.required=signup;$('#auth-form').elements.lastName.required=signup;$('#auth-form').elements.district.required=signup;$('#auth-form').elements.password.autocomplete=signup?'new-password':'current-password';$('.auth-submit').textContent=signup?'Opprett profil':'Logg inn';$('#forgot-password').hidden=signup;document.querySelectorAll('[data-auth-mode]').forEach(button=>button.setAttribute('aria-selected',String(button.dataset.authMode===mode)));showAuthMessage('');}
function openAuthDialog(mode='login'){setAuthMode(mode);$('#auth-dialog').showModal();}
function invitationURL(token){const url=new URL(location.href);url.hash='';url.searchParams.set('invite',token);return url.href;}
async function claimPendingInvitation(){if(!pendingInvitationToken||!currentSession)return null;const {data,error}=await supabase.rpc('claim_event_invitation',{invitation_token:pendingInvitationToken});if(error){console.error(error);toast(error.code==='42501'?'Logg inn med e-postadressen invitasjonen ble sendt til.':'Invitasjonslenken er ugyldig eller utløpt.');return null;}pendingInvitationToken=null;const cleanURL=new URL(location.href);cleanURL.searchParams.delete('invite');history.replaceState(null,'',cleanURL);toast('Invitasjonen er lagt til på profilen din.');return data;}
async function showInvitationPreview(){if(!pendingInvitationToken||currentSession)return;const {data,error}=await supabase.rpc('preview_event_invitation',{invitation_token:pendingInvitationToken});if(error||!data?.length){toast('Invitasjonslenken er ugyldig eller utløpt.');return;}const invitation=data[0];openAuthDialog('signup');showAuthMessage(`${invitation.inviter_name||'En Appventure-bruker'} inviterer deg til «${invitation.event_title}». Opprett konto eller logg inn med e-postadressen invitasjonen ble sendt til.`);}
function resetUser(){USER.id=null;USER.email='';USER.firstName='';USER.lastName='';USER.district='';USER.avatarPath=null;USER.customAvatar='';state.interests=new Set();state.invitations={};state.friends=[];state.friendRequests=[];updateAvatarUI();render();}
async function loadProfile(session){
 const metadata=session.user.user_metadata||{};
 let {data:profile,error}=await supabase.from('profiles').select('id, first_name, last_name, district, avatar_path, interests').eq('id',session.user.id).maybeSingle();
 if(error)throw error;
 if(!profile){const fallback={id:session.user.id,first_name:metadata.first_name||null,last_name:metadata.last_name||null,district:metadata.district||null};const result=await supabase.from('profiles').upsert(fallback).select('id, first_name, last_name, district, avatar_path, interests').single();if(result.error)throw result.error;profile=result.data;}
 USER.id=session.user.id;USER.email=session.user.email||'';USER.firstName=profile.first_name||metadata.first_name||'';USER.lastName=profile.last_name||metadata.last_name||'';USER.district=profile.district||metadata.district||'';USER.avatarPath=profile.avatar_path||null;USER.customAvatar=publicAvatarURL(USER.avatarPath);state.interests=new Set((profile.interests||[]).filter(id=>CATEGORIES.some(category=>category.id===id)));updateAvatarUI();render();
}
async function loadSocial(){const [friendships,requests]=await Promise.all([supabase.from('friendships').select('user_a, user_b, created_at'),supabase.from('friend_requests').select('id, sender_id, created_at').eq('receiver_id',USER.id).eq('status','pending').order('created_at',{ascending:false})]);if(friendships.error)throw friendships.error;if(requests.error)throw requests.error;const friendIds=friendships.data.map(row=>row.user_a===USER.id?row.user_b:row.user_a),requesterIds=requests.data.map(row=>row.sender_id),profileIds=[...new Set([...friendIds,...requesterIds])];let profiles=[];if(profileIds.length){const result=await supabase.from('profiles').select('id, first_name, last_name, district, avatar_path').in('id',profileIds);if(result.error)throw result.error;profiles=result.data;}const byId=new Map(profiles.map(profile=>[profile.id,profile]));const person=profile=>({id:profile.id,name:[profile.first_name,profile.last_name].filter(Boolean).join(' ')||'Appventure-bruker',district:profile.district||'',avatar:publicAvatarURL(profile.avatar_path)});state.friends=friendIds.map(id=>byId.get(id)).filter(Boolean).map(person);state.friendRequests=requests.data.map(request=>{const profile=byId.get(request.sender_id);return profile?{...person(profile),requestId:request.id}:null;}).filter(Boolean);}
async function applySession(session){currentSession=session;if(!session){resetUser();await loadEvents();return;}try{await loadProfile(session);await loadSocial();await claimPendingInvitation();await loadEvents();}catch(error){console.error(error);toast('Kunne ikke hente profilen. Prøv å laste siden på nytt.');}}
async function initializeAuth(){if(!hasSupabaseConfig){toast('Supabase er ikke konfigurert.');return;}supabase.auth.onAuthStateChange((event,session)=>{window.setTimeout(async()=>{await applySession(session);if(event==='PASSWORD_RECOVERY'&&!$('#password-update-dialog').open){$('#password-update-form').reset();$('#password-update-message').hidden=true;$('#password-update-dialog').showModal();}},0);});const {data,error}=await supabase.auth.getSession();if(error){toast('Kunne ikke kontrollere innloggingen.');return;}await applySession(data.session);if(!data.session)await showInvitationPreview();}
function scheduleInterestSave(){if(!currentSession)return;clearTimeout(interestSaveTimer);interestSaveTimer=setTimeout(async()=>{const {error}=await supabase.from('profiles').update({interests:[...state.interests]}).eq('id',USER.id);if(error)toast('Kunne ikke lagre interessene dine.');},450);}
function focusEvent(id){const event=state.events.find(e=>e.id===id);if(!event||!canSee(event))return;state.selected=id;renderList(filterEvents(state.events,state),state);if(map&&markers.has(id)){map.setView([event.lat,event.lng],15,{animate:false});markers.get(id).openPopup();if(innerWidth<=720)$('#map').scrollIntoView({behavior:'smooth',block:'start'});}else if(!map){$('#invite-event-name').textContent='';toast('Kartet kunne ikke lastes. Sjekk internettforbindelsen.');}}
function revealEvent(event){state.interests.add(event.category);state.query='';$('#search').value='';if(event.start.startsWith(TODAY))state.period='today';else if(event.start.startsWith(plusDays(TODAY,1)))state.period='tomorrow';else {const day=event.start.slice(0,10);if(day>=weekendStart&&day<weekendEnd)state.period='weekend';else if(day>=TODAY&&day<plusDays(TODAY,7))state.period='week';else {state.period='custom';state.customDate=day;}}render();focusEvent(event.id);}
function friendHTML(friend,type,checked=false){return `<label class="friend"><input type="checkbox" name="${type}" value="${friend.id}" ${checked?'checked':''}>${avatarImage(friend.avatarSeed,friend.name,'friend-avatar')}${esc(friend.name)}<small>Venn</small></label>`;}
let profileTab='overview';
function profileTabsHTML(){return `<div class="profile-tabs" role="tablist" aria-label="Min side"><button class="profile-tab" type="button" role="tab" data-profile-tab="overview" aria-selected="${profileTab==='overview'}">Oversikt</button><button class="profile-tab" type="button" role="tab" data-profile-tab="friends" aria-selected="${profileTab==='friends'}">Venner <span aria-hidden="true">(${state.friends.length}${state.friendRequests.length?` +${state.friendRequests.length}`:''})</span></button></div>`;}
function socialAvatar(person){return person.avatar?`<img class="friend-avatar" src="${esc(person.avatar)}" alt="Profilbilde for ${esc(person.name)}" width="48" height="48">`:avatarImage(person.id,person.name,'friend-avatar');}
function profileFriendsHTML(){const requests=state.friendRequests.map(person=>`<div class="profile-friend">${socialAvatar(person)}<div class="profile-friend-copy"><strong>${esc(person.name)}</strong><small>${esc(person.district||'Vil bli venn')}</small></div><div class="friend-request-actions"><button class="primary" data-friend-accept="${person.requestId}">Godta</button><button class="secondary" data-friend-decline="${person.requestId}">Avslå</button></div></div>`).join(''),friends=state.friends.map(person=>`<div class="profile-friend">${socialAvatar(person)}<div class="profile-friend-copy"><strong>${esc(person.name)}</strong><small>${esc(person.district||'Appventure-venn')}</small></div><button class="textbutton" data-remove-friend="${person.id}">Fjern</button></div>`).join('');return `<section role="tabpanel" aria-label="Venner"><div class="profile-friends-head"><h3>Mine venner</h3><span class="subtle">${state.friends.length} venner</span></div><form class="friend-add-form" id="friend-request-form"><label class="field">Legg til med e-post<input name="email" type="email" required autocomplete="email" placeholder="venn@eksempel.no"></label><button class="secondary" type="submit">Send venneforespørsel</button><p class="field-help">Vi avslører ikke om adressen er registrert.</p></form>${requests?`<section class="profile-section"><h3>Venneforespørsler</h3>${requests}</section>`:''}<section class="profile-section"><h3>Venneliste</h3>${friends||'<p class="subtle">Du har ikke lagt til noen venner ennå.</p>'}</section></section>`;}
function renderProfile(){
 const mine=state.events.filter(e=>e.creatorId===USER.id);
 const invitationEvents=state.events.filter(e=>Object.hasOwn(state.invitations,e.id));
 const invitationList=invitationEvents.map(event=>`<div class="invitation"><div class="eyebrow">${icon('lock')}Privat invitasjon</div><h4>${esc(event.title)}</h4><p>${esc(event.organizer)} inviterer deg<br>${dayLabel(event)} · ${timeText(event)}</p>${state.invitations[event.id]==='pending'?`<div class="invitation-actions"><button class="primary" data-accept="${event.id}">Godta</button><button class="secondary" data-decline="${event.id}">Avslå</button></div>`:`<div class="status">✓ Godtatt</div><button class="textbutton" data-mine="${event.id}">Vis i kartet →</button>`}</div>`).join('');
 const overview=`<section role="tabpanel" aria-label="Oversikt"><div class="profile-person"><div class="profile-avatar-wrap">${userAvatarImage('profile-avatar')}<button class="profile-avatar-edit" type="button" data-edit-profile aria-label="Rediger profil">${icon('edit')}</button></div><div><h3>${esc(USER.name)}</h3><p>${esc(USER.district||'Legg til bosted')}</p></div></div><section class="profile-section"><h3>Mine interesser</h3><div class="chips">${CATEGORIES.map(chipHTML).join('')}</div></section><section class="profile-section"><h3>Mine arrangementer <span class="subtle">(${mine.length})</span></h3>${mine.map(e=>`<button class="mine-item" data-mine="${e.id}">${esc(e.title)}<small>${dayLabel(e)} · ${e.visibility==='private'?'Privat':'Offentlig'}</small></button>`).join('')||'<p class="subtle">Du har ikke opprettet noen arrangementer ennå.</p>'}</section>${invitationList?`<section class="profile-section"><h3>Invitasjoner</h3>${invitationList}</section>`:''}<section class="profile-account"><p class="subtle profile-email">Innlogget som ${esc(USER.email)}</p><div class="profile-account-actions"><button type="button" class="secondary" data-logout>Logg ut</button><button type="button" class="textbutton danger-link" data-delete-account>Slett konto</button></div></section></section>`;
 $('#profile-body').innerHTML=profileTabsHTML()+(profileTab==='friends'?profileFriendsHTML():overview);
}
let pendingAvatarFile=null,removeAvatar=false,avatarPreviewURL='';
function openProfileEditor(){const form=$('#profile-edit-form');form.elements.firstName.value=USER.firstName;form.elements.lastName.value=USER.lastName;form.elements.district.value=USER.district;$('#avatar-upload').value='';pendingAvatarFile=null;removeAvatar=false;if(avatarPreviewURL)URL.revokeObjectURL(avatarPreviewURL);avatarPreviewURL='';$('#avatar-preview').src=userAvatarURL();$('#avatar-remove').hidden=!USER.avatarPath;$('#profile-edit-dialog').showModal();}
function closeDialog(id){$('#'+id).close();}
function openCreate(){const form=$('#event-form');form.reset();form.elements.date.value=TODAY;form.elements.date.min=TODAY;state.editingEventId=null;state.draftLocation=null;state.draftImage=EVENT_IMAGES[0].src;state.draftImagePreset='green';state.draftExistingImagePath=null;state.draftRemoveImage=false;draftEventImageFile=null;$('#create-title').textContent='Noe på gang?';form.querySelector('[type="submit"]').firstChild.textContent='Opprett event';renderEventImagePresets();$('#event-image-preview').hidden=true;$('#event-image-preview').removeAttribute('src');$('#event-image-remove').hidden=true;if(draftMarker){draftMarker.remove();draftMarker=null;}$('#location-status').textContent='Ingen kartposisjon valgt.';$('#private-friends').hidden=true;$('#create-dialog').showModal();}
function openEditEvent(event){const form=$('#event-form');form.reset();state.editingEventId=event.id;state.draftLocation={lat:event.lat,lng:event.lng};state.draftImagePreset=event.imagePreset||'green';state.draftExistingImagePath=event.imagePath||null;state.draftRemoveImage=false;draftEventImageFile=null;state.draftImage=event.imagePath?event.image:(EVENT_IMAGES.find(image=>image.id===state.draftImagePreset)?.src||EVENT_IMAGES[0].src);form.elements.title.value=event.title;form.elements.category.value=event.category;form.elements.description.value=event.description;form.elements.date.value=event.start.slice(0,10);form.elements.date.min=TODAY;form.elements.price.value=event.price==='Gratis'?'':event.price;form.elements.start.value=event.start.slice(11,16);form.elements.end.value=event.end.slice(11,16);form.elements.venue.value=event.venue;form.elements.visibility.value=event.visibility;$('#create-title').textContent='Rediger arrangement';form.querySelector('[type="submit"]').firstChild.textContent='Lagre endringer';renderEventImagePresets();$('#event-image-preview').hidden=!event.imagePath;$('#event-image-preview').src=event.imagePath?event.image:'';$('#event-image-remove').hidden=!event.imagePath;$('#location-status').textContent=`Kartpunkt valgt: ${event.lat.toFixed(4)}, ${event.lng.toFixed(4)}.`;$('#private-friends').hidden=event.visibility!=='private';$('#create-dialog').showModal();}
function stopPicking(){state.picking=false;$('.map-shell').classList.remove('picking');$('#pick-bar').hidden=true;if(draftMarker){draftMarker.remove();draftMarker=null;}$('#create-dialog').showModal();if(state.draftLocation)$('#location-status').textContent=`Kartpunkt valgt: ${state.draftLocation.lat.toFixed(4)}, ${state.draftLocation.lng.toFixed(4)}.`;}
function initMap(){
 if(!window.L){$('#map-error').hidden=false;$('#map-error').textContent='Kartet kunne ikke lastes. Leaflet og kartflisene trenger internett. Filtre, profil og eventskjema fungerer fortsatt.';$('#pick-start').disabled=true;return;}
 map=L.map('map',{zoomControl:false,minZoom:11,maxZoom:18,maxBounds:[[59.78,10.48],[60.04,11.04]],maxBoundsViscosity:1}).setView(CENTER,13);
 tileLayer=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>',maxZoom:19}).addTo(map);
 let loadedTiles=0;tileLayer.on('tileload',()=>{loadedTiles++;$('#map-error').hidden=true;});tileLayer.on('tileerror',()=>{if(!loadedTiles){$('#map-error').hidden=false;$('#map-error').textContent='Kartflisene er ikke tilgjengelige akkurat nå. Sjekk internettforbindelsen. Markører og filtre fungerer fortsatt.';}});
 markerLayer=L.layerGroup().addTo(map);L.control.zoom({position:'bottomright',zoomInTitle:'Zoom inn',zoomOutTitle:'Zoom ut'}).addTo(map);
 map.on('click',e=>{if(!state.picking)return;state.draftLocation={lat:e.latlng.lat,lng:e.latlng.lng};if(draftMarker)draftMarker.setLatLng(e.latlng);else draftMarker=L.marker(e.latlng,{icon:L.divIcon({className:'map-pin',html:'<div class="pin-core" style="--category:#333"><span>+</span></div>',iconSize:[30,36],iconAnchor:[15,33]})}).addTo(map);$('#pick-done').disabled=false;$('#pick-instruction').textContent='Punkt valgt. Klikk et annet sted for å flytte det.';});
}
$('#today-label').textContent=dateText(TODAY,{weekday:'long',day:'numeric',month:'long'});
$('#category-select').innerHTML=CATEGORIES.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');
$('#search').addEventListener('input',e=>{state.query=e.target.value;render();});
$('#select-all').addEventListener('click',()=>{state.interests=state.interests.size===CATEGORIES.length?new Set():new Set(CATEGORIES.map(c=>c.id));render();scheduleInterestSave();});
$('#interest-toggle').addEventListener('click',()=>{const panel=$('#interest-panel'),willOpen=panel.hidden;panel.hidden=!willOpen;$('#interest-toggle').setAttribute('aria-expanded',String(willOpen));if(willOpen)panel.querySelector('.chip')?.focus();});
$('#interest-done').addEventListener('click',()=>{$('#interest-panel').hidden=true;$('#interest-toggle').setAttribute('aria-expanded','false');$('#interest-toggle').focus();});
$('#profile-open').addEventListener('click',async()=>{if(!currentSession){openAuthDialog();return;}try{await loadSocial()}catch(error){console.error(error);toast('Kunne ikke oppdatere vennelisten.');}renderProfile();$('#profile-dialog').showModal();});
$('#auth-form').addEventListener('submit',async e=>{e.preventDefault();if(!supabase)return;const form=e.target,values=new FormData(form),email=values.get('email').trim(),password=values.get('password'),submit=$('.auth-submit');submit.disabled=true;showAuthMessage('');try{if(authMode==='signup'){const firstName=values.get('firstName').trim(),lastName=values.get('lastName').trim(),district=values.get('district').trim();if(!firstName||!lastName||!district){showAuthMessage('Fyll inn navn og bosted.',true);return;}const redirectURL=pendingInvitationToken?invitationURL(pendingInvitationToken):location.origin;const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:redirectURL,data:{first_name:firstName,last_name:lastName,district}}});if(error)throw error;if(data.session){await applySession(data.session);closeDialog('auth-dialog');toast('Profilen er opprettet.');}else{form.elements.password.value='';showAuthMessage('Sjekk e-posten din og bekreft kontoen. Du sendes tilbake til invitasjonen etter bekreftelse.');}}else{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;await applySession(data.session);closeDialog('auth-dialog');form.reset();toast(`Velkommen, ${USER.firstName||'du'}!`);}}catch(error){showAuthMessage(authErrorMessage(error),true);}finally{submit.disabled=false;}});
$('#forgot-password').addEventListener('click',async()=>{if(!supabase)return;const email=$('#auth-form').elements.email.value.trim(),button=$('#forgot-password');if(!email){showAuthMessage('Skriv inn e-postadressen din først.',true);$('#auth-form').elements.email.focus();return;}button.disabled=true;showAuthMessage('');try{const redirectTo=`${location.origin}${location.pathname}`;const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo});if(error)throw error;showAuthMessage('Hvis adressen er registrert, får du en e-post med lenke for å velge nytt passord.');}catch(error){showAuthMessage(authErrorMessage(error),true);}finally{button.disabled=false;}});
$('#password-update-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target,password=form.elements.password.value,confirmation=form.elements.passwordConfirm.value,message=$('#password-update-message'),submit=form.querySelector('[type="submit"]');message.hidden=true;if(password!==confirmation){message.textContent='Passordene er ikke like.';message.classList.add('error');message.hidden=false;return;}submit.disabled=true;try{const {error}=await supabase.auth.updateUser({password});if(error)throw error;closeDialog('password-update-dialog');form.reset();toast('Passordet er oppdatert. Du er nå logget inn.');}catch(error){message.textContent=authErrorMessage(error);message.classList.add('error');message.hidden=false;}finally{submit.disabled=false;}});
$('#privacy-open').addEventListener('click',()=>$('#privacy-dialog').showModal());
$('#delete-account-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target,confirmation=form.elements.confirmation.value,submit=form.querySelector('[type="submit"]'),message=$('#delete-account-message');message.hidden=true;if(confirmation!=='SLETT'){message.textContent='Skriv SLETT med store bokstaver.';message.classList.add('error');message.hidden=false;return;}submit.disabled=true;try{const {error}=await supabase.functions.invoke('delete-account',{body:{confirmation}});if(error)throw error;await supabase.auth.signOut({scope:'local'});closeDialog('delete-account-dialog');if($('#profile-dialog').open)closeDialog('profile-dialog');form.reset();await applySession(null);toast('Kontoen og innholdet ditt er slettet.');}catch(error){console.error(error);message.textContent='Kontoen kunne ikke slettes. Prøv igjen.';message.classList.add('error');message.hidden=false;}finally{submit.disabled=false;}});
$('#avatar-upload').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(!ALLOWED_IMAGE_TYPES.has(file.type)){toast('Velg JPG, PNG, WebP eller GIF.');e.target.value='';return;}if(file.size>1.5*1024*1024){toast('Bildet er for stort. Velg et bilde under 1,5 MB.');e.target.value='';return;}if(avatarPreviewURL)URL.revokeObjectURL(avatarPreviewURL);avatarPreviewURL=URL.createObjectURL(file);pendingAvatarFile=file;removeAvatar=false;$('#avatar-preview').src=avatarPreviewURL;$('#avatar-remove').hidden=false;});
$('#avatar-remove').addEventListener('click',()=>{pendingAvatarFile=null;removeAvatar=true;if(avatarPreviewURL)URL.revokeObjectURL(avatarPreviewURL);avatarPreviewURL='';$('#avatar-upload').value='';$('#avatar-preview').src=avatarURL(USER.id||'guest');$('#avatar-remove').hidden=true;});
$('#profile-edit-form').addEventListener('submit',async e=>{e.preventDefault();if(!currentSession)return;const form=e.target,values=new FormData(form),firstName=values.get('firstName').trim(),lastName=values.get('lastName').trim(),district=values.get('district').trim(),submit=form.querySelector('[type="submit"]');if(!firstName||!lastName||!district)return;submit.disabled=true;let nextAvatarPath=removeAvatar?null:USER.avatarPath;try{if(pendingAvatarFile){const extension={"image/jpeg":'jpg',"image/png":'png',"image/webp":'webp',"image/gif":'gif'}[pendingAvatarFile.type];nextAvatarPath=`${USER.id}/avatar-${Date.now()}.${extension}`;const upload=await supabase.storage.from('avatars').upload(nextAvatarPath,pendingAvatarFile,{contentType:pendingAvatarFile.type,upsert:false});if(upload.error)throw upload.error;}const update=await supabase.from('profiles').update({first_name:firstName,last_name:lastName,district,avatar_path:nextAvatarPath}).eq('id',USER.id).select('first_name, last_name, district, avatar_path').single();if(update.error)throw update.error;const previousAvatarPath=USER.avatarPath;USER.firstName=update.data.first_name;USER.lastName=update.data.last_name;USER.district=update.data.district;USER.avatarPath=update.data.avatar_path;USER.customAvatar=publicAvatarURL(USER.avatarPath);state.events.filter(event=>event.creatorId===USER.id).forEach(event=>event.organizer=USER.name);if(previousAvatarPath&&previousAvatarPath!==USER.avatarPath)await supabase.storage.from('avatars').remove([previousAvatarPath]);updateAvatarUI();renderProfile();closeDialog('profile-edit-dialog');toast('Profilen er oppdatert.');}catch(error){console.error(error);toast('Kunne ikke lagre profilen. Prøv igjen.');}finally{submit.disabled=false;}});
$('#create-open').addEventListener('click',()=>{if(!currentSession){openAuthDialog('signup');toast('Opprett en profil for å lage arrangementer.');return;}openCreate();});
$('#event-image-upload').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(!ALLOWED_IMAGE_TYPES.has(file.type)){toast('Velg JPG, PNG, WebP eller GIF.');e.target.value='';return;}if(file.size>3*1024*1024){toast('Bildet er for stort. Velg et bilde under 3 MB.');e.target.value='';return;}const reader=new FileReader();reader.onload=()=>{draftEventImageFile=file;state.draftRemoveImage=false;state.draftImage=reader.result;renderEventImagePresets();$('#event-image-preview').src=state.draftImage;$('#event-image-preview').hidden=false;$('#event-image-remove').hidden=false;};reader.onerror=()=>toast('Bildet kunne ikke leses.');reader.readAsDataURL(file);});
$('#event-image-remove').addEventListener('click',()=>{draftEventImageFile=null;state.draftRemoveImage=true;state.draftImagePreset='green';state.draftImage=EVENT_IMAGES[0].src;renderEventImagePresets();$('#event-image-upload').value='';$('#event-image-preview').hidden=true;$('#event-image-preview').removeAttribute('src');$('#event-image-remove').hidden=true;});
$('#share-copy').addEventListener('click',async()=>{const input=$('#share-link');try{await navigator.clipboard.writeText(input.value)}catch{input.focus();input.select();document.execCommand('copy')}toast('Lenken er kopiert.');});
$('#event-form').addEventListener('change',e=>{if(e.target.name==='visibility')$('#private-friends').hidden=e.target.value!=='private';});
$('#pick-start').addEventListener('click',()=>{closeDialog('create-dialog');state.picking=true;$('.map-shell').classList.add('picking');$('#pick-bar').hidden=false;$('#pick-done').disabled=!state.draftLocation;$('#pick-instruction').textContent=state.draftLocation?'Kartpunkt er valgt. Klikk for å flytte det.':'Klikk i kartet for å plassere eventet.';if(state.draftLocation){draftMarker=L.marker(state.draftLocation,{icon:L.divIcon({className:'map-pin',html:'<div class="pin-core" style="--category:#333"><span>+</span></div>',iconSize:[30,36],iconAnchor:[15,33]})}).addTo(map);}if(innerWidth<=720)$('#map').scrollIntoView({behavior:'smooth'});$('#pick-cancel').focus();});
$('#pick-done').addEventListener('click',stopPicking);$('#pick-cancel').addEventListener('click',stopPicking);
$('#event-form').addEventListener('submit',async e=>{
 e.preventDefault();const form=e.target,values=new FormData(form),title=values.get('title').trim(),description=values.get('description').trim(),venue=values.get('venue').trim();
 if(!title||!description){toast('Fyll inn tittel og beskrivelse.');return;}
 if(!venue&&!state.draftLocation){toast('Skriv et stedsnavn eller velg et punkt i kartet.');$('#venue-input').focus();return;}
 const endDate=values.get('end')<=values.get('start')?plusDays(values.get('date'),1):values.get('date');
 const location=state.draftLocation||{lat:CENTER[0],lng:CENTER[1]};
 const preset=state.draftImagePreset||EVENT_IMAGES.find(image=>image.src===state.draftImage)?.id||'green',submit=form.querySelector('[type="submit"]'),editingId=state.editingEventId;submit.disabled=true;let eventId=editingId||crypto.randomUUID(),imageWarning=false,newImagePath=null;
 const payload={title,description,category:values.get('category'),starts_at:localDateTimeISO(values.get('date'),values.get('start')),ends_at:localDateTimeISO(endDate,values.get('end')),venue:venue||'Valgt sted i Oslo',latitude:location.lat,longitude:location.lng,price_text:values.get('price').trim()||'Gratis',visibility:values.get('visibility'),status:'published',image_preset:preset};
 try{
  if(!editingId){const insert=await supabase.from('events').insert({id:eventId,creator_id:USER.id,...payload});if(insert.error)throw insert.error;}
  if(draftEventImageFile){const extension={"image/jpeg":'jpg',"image/png":'png',"image/webp":'webp',"image/gif":'gif'}[draftEventImageFile.type];newImagePath=`${eventId}/event-${Date.now()}.${extension}`;const upload=await supabase.storage.from('event-images').upload(newImagePath,draftEventImageFile,{contentType:draftEventImageFile.type,upsert:false});if(upload.error){if(editingId)throw upload.error;imageWarning=true;newImagePath=null;}}
  if(editingId){const nextImagePath=newImagePath||(state.draftRemoveImage?null:state.draftExistingImagePath);const update=await supabase.from('events').update({...payload,image_path:nextImagePath}).eq('id',editingId);if(update.error)throw update.error;if(state.draftExistingImagePath&&state.draftExistingImagePath!==nextImagePath)await supabase.storage.from('event-images').remove([state.draftExistingImagePath]);}
  else if(newImagePath){const update=await supabase.from('events').update({image_path:newImagePath}).eq('id',eventId);if(update.error){await supabase.storage.from('event-images').remove([newImagePath]);imageWarning=true;}}
  await loadEvents();const event=state.events.find(item=>item.id===eventId);closeDialog('create-dialog');if(event)revealEvent(event);toast(editingId?'Arrangementet er oppdatert.':imageWarning?'Arrangementet ble lagret, men bildet kunne ikke lastes opp.':'Arrangementet er opprettet og lagret.');
 }catch(error){console.error(error);if(newImagePath)await supabase.storage.from('event-images').remove([newImagePath]);toast(`${editingId?'Kunne ikke oppdatere':'Kunne ikke opprette'}: ${eventErrorMessage(error)}`);}finally{submit.disabled=false;}
});
$('#invite-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target,email=new FormData(form).get('email').trim(),submit=form.querySelector('[type="submit"]');submit.disabled=true;const {data:token,error}=await supabase.rpc('create_event_invitation_link',{requested_event_id:state.inviteEvent,invitee_email:email});if(error){submit.disabled=false;console.error(error);toast(`Kunne ikke invitere: ${eventErrorMessage(error)}`);return;}const link=invitationURL(token);$('#invite-link').value=link;$('#invite-link-result').hidden=false;$('#invite-delivery-status').textContent='Sender e-post …';const {error:sendError}=await supabase.functions.invoke('send-event-invitation',{body:{eventId:state.inviteEvent,email,token}});submit.disabled=false;if(sendError){console.error(sendError);$('#invite-delivery-status').textContent='E-posten kunne ikke sendes. Kopier og del lenken manuelt.';toast('Lenken er klar, men e-posten kunne ikke sendes.');return;}$('#invite-delivery-status').textContent='Invitasjonen er sendt. Du kan også kopiere lenken manuelt.';toast('Invitasjonen er sendt på e-post.');});
$('#invite-copy').addEventListener('click',async()=>{const input=$('#invite-link');try{await navigator.clipboard.writeText(input.value)}catch{input.focus();input.select();document.execCommand('copy')}toast('Invitasjonslenken er kopiert.');});
document.addEventListener('submit',async e=>{if(e.target.id!=='friend-request-form')return;e.preventDefault();const form=e.target,email=new FormData(form).get('email').trim(),submit=form.querySelector('[type="submit"]');submit.disabled=true;const {error}=await supabase.rpc('send_friend_request',{requested_email:email});submit.disabled=false;if(error){console.error(error);toast(`Kunne ikke sende forespørselen: ${eventErrorMessage(error)}`);return;}form.reset();toast('Venneforespørselen er registrert dersom brukeren finnes.');});
document.addEventListener('click',async e=>{
 const button=e.target.closest('button');if(!button)return;const d=button.dataset;
 if(d.close)closeDialog(d.close);
 if(d.authMode)setAuthMode(d.authMode);
 if(d.profileTab){profileTab=d.profileTab;renderProfile();$('#profile-body').querySelector(`[data-profile-tab="${d.profileTab}"]`)?.focus();}
 if(d.category){const focusedCategory=d.category,profile=$('#profile-dialog').open;state.interests.has(d.category)?state.interests.delete(d.category):state.interests.add(d.category);render();scheduleInterestSave();(profile?$('#profile-body'):$('#interests')).querySelector(`[data-category="${focusedCategory}"]`)?.focus({preventScroll:true});}
 if(d.time){state.period=d.time;render();}
 if(d.event)focusEvent(d.event);
 if(button.id==='clear-search'){state.query='';$('#search').value='';render();}
 if(d.eventImage){const option=EVENT_IMAGES.find(image=>image.id===d.eventImage);if(option){draftEventImageFile=null;state.draftRemoveImage=Boolean(state.draftExistingImagePath);state.draftImagePreset=option.id;state.draftImage=option.src;renderEventImagePresets();$('#event-image-upload').value='';$('#event-image-preview').hidden=true;$('#event-image-preview').removeAttribute('src');$('#event-image-remove').hidden=true;$('#event-image-presets').querySelector(`[data-event-image="${d.eventImage}"]`)?.focus();}}
 if(d.share){const event=state.events.find(item=>item.id===d.share);if(event)shareEvent(event);}
 if(d.editEvent){const event=state.events.find(item=>item.id===d.editEvent);if(event?.creatorId===USER.id){map?.closePopup();openEditEvent(event);}}
 if(d.deleteEvent){const event=state.events.find(item=>item.id===d.deleteEvent);if(event?.creatorId===USER.id&&confirm(`Slette «${event.title}»? Dette kan ikke angres.`)){button.disabled=true;const deletion=await supabase.from('events').delete().eq('id',event.id);if(deletion.error){button.disabled=false;toast(`Kunne ikke slette: ${eventErrorMessage(deletion.error)}`);return;}if(event.imagePath)await supabase.storage.from('event-images').remove([event.imagePath]);map?.closePopup();await loadEvents();toast('Arrangementet er slettet.');}}
 if(d.participants){const event=state.events.find(item=>item.id===d.participants);if(event)openParticipants(event);}
 if(Object.hasOwn(d,'editProfile'))openProfileEditor();
 if(Object.hasOwn(d,'deleteAccount')){$('#delete-account-form').reset();$('#delete-account-message').hidden=true;$('#delete-account-dialog').showModal();}
 if(d.going){state.going.has(d.going)?state.going.delete(d.going):state.going.add(d.going);const event=state.events.find(ev=>ev.id===d.going);markers.get(d.going)?.setPopupContent(popupHTML(event));}
 if(d.invite){state.inviteEvent=d.invite;const event=state.events.find(ev=>ev.id===d.invite);$('#invite-event-name').textContent=event.title;$('#invite-form').reset();$('#invite-link-result').hidden=true;$('#invite-link').value='';$('#invite-friend-section').hidden=!state.friends.length;$('#invite-friend-list').innerHTML=state.friends.map(friend=>`<div class="profile-friend">${socialAvatar(friend)}<div class="profile-friend-copy"><strong>${esc(friend.name)}</strong><small>${esc(friend.district||'Venn')}</small></div><button class="secondary" type="button" data-invite-friend="${friend.id}">Inviter</button></div>`).join('');$('#invite-dialog').showModal();}
 if(d.friendAccept||d.friendDecline){const requestId=d.friendAccept||d.friendDecline,status=d.friendAccept?'accepted':'declined';button.disabled=true;const {error}=await supabase.rpc('respond_to_friend_request',{requested_request_id:requestId,requested_status:status});if(error){button.disabled=false;toast('Kunne ikke svare på venneforespørselen.');return;}await loadSocial();renderProfile();toast(status==='accepted'?'Dere er nå venner.':'Venneforespørselen er avslått.');}
 if(d.removeFriend&&confirm('Fjerne denne personen fra vennelisten?')){button.disabled=true;const {error}=await supabase.rpc('remove_friend',{requested_friend_id:d.removeFriend});if(error){button.disabled=false;toast('Kunne ikke fjerne vennen.');return;}await loadSocial();renderProfile();toast('Personen er fjernet fra vennelisten.');}
 if(d.inviteFriend){button.disabled=true;const {error}=await supabase.rpc('invite_friend_to_event',{requested_event_id:state.inviteEvent,requested_friend_id:d.inviteFriend});button.disabled=false;if(error){toast(`Kunne ikke invitere: ${eventErrorMessage(error)}`);return;}closeDialog('invite-dialog');toast('Vennen er invitert i Appventure.');}
 if(d.accept){const response=await supabase.from('event_invitations').update({status:'accepted'}).eq('event_id',d.accept).eq('invitee_id',USER.id);if(response.error){toast('Kunne ikke godta invitasjonen.');return;}await loadEvents();closeDialog('profile-dialog');const event=state.events.find(ev=>ev.id===d.accept);if(event)revealEvent(event);toast('Invitasjonen er godtatt.');}
 if(d.decline){const response=await supabase.from('event_invitations').update({status:'declined'}).eq('event_id',d.decline).eq('invitee_id',USER.id);if(response.error){toast('Kunne ikke avslå invitasjonen.');return;}await loadEvents();toast('Invitasjonen er avslått.');}
 if(d.mine){closeDialog('profile-dialog');revealEvent(state.events.find(ev=>ev.id===d.mine));}
 if(Object.hasOwn(d,'logout')){button.disabled=true;const {error}=await supabase.auth.signOut();if(error){button.disabled=false;toast('Kunne ikke logge ut. Prøv igjen.');return;}closeDialog('profile-dialog');toast('Du er logget ut.');}
});
for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.picking)stopPicking();});
updateAvatarUI();initMap();render();await initializeAuth();
